# Generated by Django 4.1.3 on 2022-12-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('name_surname', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='animal_picture')),
                ('pet_type', models.CharField(max_length=30)),
                ('pet_genus', models.CharField(max_length=30)),
                ('pet_name', models.CharField(max_length=30)),
                ('pet_age', models.IntegerField(blank=True)),
                ('explanation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=30, unique=True)),
                ('contact_infos', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('email_field', models.EmailField(max_length=30, unique=True)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='vet.petmodel')),
            ],
            options={
                'verbose_name': 'Owner',
                'db_table': 'owner',
            },
        ),
    ]
