# Generated by Django 4.1.3 on 2022-12-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='name_surname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='vet.petmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(default='some_value', max_length=30),
        ),
        migrations.DeleteModel(
            name='OwnerModel',
        ),
    ]
